print("Hello Biatchhhhhh!!!!")
print("Hello Biatchhhhhh!!!!")
print("Hello Biatchhhhhh!!!!")
print("Hello Biatchhhhhh!!!!")
print("Hello Biatchhhhhh!!!!")
print("Hello Biatchhhhhh!!!!")
print("hi ")
print(gandu)
